
# Based on Canonical's Guidelines
# https://docs.google.com/document/d/1mJUa1VJHOMWa723dmKmNjSKGW-nlBv9xktzGZZwacVo/edit#heading=h.5efudb237qdb
rules:
  - name: whitelist
    terms:
      - whitelist
      - white-list
      - whitelisted
      - white-listed
    alternatives:
      - allowlist
      - inclusion list
    severity: warning
    note: "The underlying assumption of the whitelist/blacklist metaphor is that white = good and black = bad. Because colors in and of themselves have no predetermined meaning, any meaning we assign to them is cultural: for example, the color red in many Southeast Asian countries is lucky, and is often associated with events like marriages, whereas the color white carries the same connotations in many European countries. In the case of whitelist/blacklist, the terms originate in the publishing industry – one dominated by the USA and England, two countries which participated in slavery and which grapple with their racist legacies to this day."

  - name: blacklist
    terms:
      - blacklist
      - black-list
      - blacklisted
      - black-listed
    alternatives:
      - denylist
      - blocklist
      - exclusion list
    severity: warning
    note: "The underlying assumption of the whitelist/blacklist metaphor is that white = good and black = bad. Because colors in and of themselves have no predetermined meaning, any meaning we assign to them is cultural: for example, the color red in many Southeast Asian countries is lucky, and is often associated with events like marriages, whereas the color white carries the same connotations in many European countries. In the case of whitelist/blacklist, the terms originate in the publishing industry – one dominated by the USA and England, two countries which participated in slavery and which grapple with their racist legacies to this day."

  - name: master-slave
    terms:
      - master-slave
      - master/slave
    alternatives:
      - leader/follower
      - main/replica
      - primary/replica
      - primary/standby
      - primary/secondary

  - name: slave
    terms:
      - slave
    alternatives:
      - follower
      - replica
      - standby

  - name: grandfathered
    terms:
      - grandfathered
    alternatives:
      - legacy status
      - legacied
      - exempted
      - carried
      - brought forward
      - rolled over

  - name: man-hours
    terms:
      - man hours
      - man-hours
    alternatives:
      - person hours
      - engineer hours

  - name: sanity
    terms:
      - sanity
    alternatives:
      - confidence
      - quick check
      - coherence check

  - name: dummy
    terms:
      - dummy
    alternatives:
      - placeholder
      - sample

  - name: guys
    terms:
      - guys
    alternatives:
      - folks
      - people
      - you all
      - y'all
      - yinz

  - name: whitebox
    terms:
      - white-box
      - whitebox
      - white box
    alternatives:
      - open-box

  - name: blackbox
    terms:
      - black-box
      - blackbox
      - black box
    alternatives:
      - closed-box

  - name: blackhat
    terms:
      - blackhat
      - black-hat
      - black hat
    alternatives:
      - attacker
      - malicious actor

  - name: whitehat
    terms:
      - whitehat
      - white-hat
      - white hat
    alternatives:
      - researcher
      - security specialist

  - name: illegal characters
    terms:
      - illegal characters
    alternatives:
      - invalid characters
      - unsupported characters
      - special characters

  - name: native feature
    terms:
      - native feature
    alternatives:
      - core feature
      - built-in feature

  - name: chairman/foreman
    terms:
      - chairman
      - foreman
    alternatives:
      - chair
      - foreperson

  - name: man in the middle
    terms:
      - man in the middle
      - man-in-the-middle
    alternatives:
      - machine-in-the-middle
      - person-in-the-middle
      - system-in-the-middle
      - intermediary attack

  - name: middleman
    terms:
      - middleman
    alternatives:
      - middleperson
      - intermediary

  - name: manned
    terms:
      - manned
    alternatives:
      - crewed
      - staffed
      - monitored
      - human operated

  - name: mom test / girlfriend test
    terms:
      - mom test
      - girlfriend test
    alternatives:
      - user test
      - user friendly

  - name: crazy
    terms:
      - crazy
    alternatives:
      - baffling
      - unexplained
      - errant

  - name: cripples
    terms:
      - cripples
    alternatives:
      - slows down
      - hinders
      - obstructs

  - name: crippling
    terms:
      - crippling
    alternatives:
      - attenuating
      - incapacitating

  - name: stonith/stomith
    terms:
      - stonith
      - stomith
    alternatives:
      - fence failed nodes
      - machines

  - name: demilitarized zone
    terms:
      - demilitarized zone
      - dmz
    alternatives:
      - perimeter network
      - passthrough network
