#!/usr/bin/python

import sys

rejected = False

for ref_line in sys.stdin.readlines():
    old, new, ref = ref_line.rstrip(b'\n').split(b' ', 2)
    if ref.endswith(b'verboten'):
        print b"You can't push to %s." % ref
        rejected = True

sys.exit(1 if rejected else 0)
