#! /bin/sh
set -u

. /usr/lib/nagios/plugins/utils.sh

LOGFILE=/var/log/nagios/check_git_refs.log

if [ -z "$1" ]; then
    echo "Usage: check_git_refs REPOSITORY_URL"
    exit $STATE_UNKNOWN
fi

if ! BRANCHES="$(git ls-remote -h "$1" 2>$LOGFILE)"; then
    echo "CRITICAL: Cannot list branches in $1"
    exit $STATE_CRITICAL
fi

if ! echo "$BRANCHES" | grep -q '[[:space:]]refs/heads/'; then
    echo "CRITICAL: $1 has no heads"
    exit $STATE_CRITICAL
fi

echo "OK: Master branch found in $1"
exit $STATE_OK
